<a href="https://colab.research.google.com/github/Saiji/Data-Science-Work/blob/master/EDA2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("/content/Generate Professor Data for Practice.csv")

In [7]:
df

                    Name                 Rank  Experience  Age  Salary
0   Dr. Deborah Mitchell            Professor          32   65  195000
1      Dr. Lisa Thompson  Associate Professor          17   50  124000
2        Robert Williams  Assistant Professor           4   32   78000
3        Dr. Sarah Allen            Professor          31   64  190000
4         Jennifer Jones  Assistant Professor           2   29   71000
..                   ...                  ...         ...  ...     ...
95   Dr. Michelle Walker            Professor          21   53  151000
96    Dr. Cynthia Nelson  Associate Professor          10   41  101000
97      Alexander Foster  Assistant Professor           6   36   86500
98    Dr. Justin Roberts            Professor          20   52  148000
99   Dr. Christina Kelly  Associate Professor          10   41  102500

[100 rows x 5 columns]

In [22]:
df.groupby('Rank').mean('Age')

                     Experience        Age         Salary
Rank
Assistant Professor    4.343750  33.250000   80937.500000
Associate Professor   13.352941  46.588235  113632.352941
Professor             25.705882  58.470588  169764.705882